parameters:
  - name: timestamp
    displayName: Timestamp
    type: string
  - name: teamName
    displayName: Team Name
    type: string
  - name: serviceName
    displayName: Service Name
    type: string
  - name: serviceVersion
    displayName: Service Version
    type: string
  - name: state
    displayName: State
    type: string
    values:
      - Canceling
      - Completed
      - InProgress
      - Unknown
  - name: result
    displayName: Result
    type: string
    values:
      - Canceled
      - Failed
      - Succeeded
      - Unknown

jobs:
  - job: SendPipelineExecutionEvent
    displayName: Send Pipeline Execution Event
    pool: server
    steps:
      - task: InvokeRESTAPI@1
        inputs:
          connectionType: "connectedServiceName"
          serviceConnection: "https://mp-sdo-proto.servicebus.windows.net/mp-sdo-proto-eventhub/messages"
          method: "POST"
          headers: |
            {
              "Host": "mp-sdo-proto.servicebus.windows.net",
              "Content-Type": "application/x-www-form-urlencoded",
              "Authorization": "$(MP-SDO-PROTO-EVENTHUB-SAS)"          
            }
          body: |
            {
                "source": "Azure DevOps",
                "type": "PipelineExecutionEvent",
                "sourceId": "$(Build.DefinitionName)-$(Build.BuildId)",
                "timestamp": "${{ parameters.timestamp }}",
                "payload": {
                    "name": "$(Build.DefinitionName)",
                    "runId": "$(Build.BuildId)",
                    "teamName": "${{ parameters.teamName }}",
                    "serviceName": "${{ parameters.serviceName }}",
                    "serviceVersion": "${{ parameters.serviceVersion }}",
                    "repoName": "$(Build.Repository.Name)",
                    "branchName": "$(Build.SourceBranchName)",
                    "commitHash": "$(Build.SourceVersion)",
                    "state": "${{ parameters.state }}",
                    "result": "${{ parameters.result }}"
                }
            }
          waitForCompletion: "false"
